// Turkish-to-English translation dictionary (Combined for performance and cleaner codebase)
export const trToEnMap: Record<string, string> = {
  "== COMMON & NAVIGATION ==": "",
  "DOWNLOAD": "DOWNLOAD",
  "Ölçüm Yap": "Survey",
  "Aplikasyon Yap": "Stake Out",
  "Kayıtlı Ölçümler": "Saved Surveys",
  "Veri Aktar": "Export Data",
  "Yardım": "Help",
  "Ayarlar": "Settings",
  "Kayıt Edildi": "Saved",
  "Uygulamaya Başla": "Start Application",
  "Lütfen Bekleyin...": "Please Wait...",
  "Lütfen bekleyin...": "Please wait...",
  "Dil Değiştir": "Change Language",
  "Uygulama Ayarları": "Application Settings",
  "Mobil Cihazlarınız için Konum Belirleme Uygulaması": "Location Positioning App for Your Mobile Devices",
  "Mobil Cihazlarınız için\nKonum Belirleme Uygulaması": "Location Positioning App\nfor Your Mobile Devices",
  "Mobil Cihazlarınız için": "for Your Mobile Devices",
  "Konum Belirleme Uygulaması": "Location Positioning App",
  "Konum İzni": "Location Permission",
  "Gerekli": "Required",
  "Desteklenmiyor": "Not Supported",
  "Konum İzni\nGerekli": "Location Permission\nRequired",
  "Tarayıcınız konum servisini desteklemiyor. Lütfen farklı bir tarayıcı deneyin veya cihaz ayarlarınızı kontrol edin.": "Your browser does not support location services. Please try a different browser or check device settings.",
  "1. Android Kullanıcıları": "1. Android Users",
  "Üst bildiri panelinden konum servislerini aktif hale getirin.": "Enable location services from the top notification panel.",
  "2. iOS Kullanıcıları": "2. iOS Users",
  "Ayarlar-Konum-Safari Siteleri-Konum iznini aktif hale getirin.": "Settings -> Location -> Safari Websites -> Enable Location Access.",
  "Tekrar Dene": "Retry",
  "İzni Tekrar Kontrol Et": "Check Permission Again",
  "İptal": "Cancel",
  "Kapat": "Close",

  "== ONBOARDING ==": "",
  "Açılışta bu ekranı atla": "Skip this screen on startup",
  "Konum Erişimi": "Location Access",
  "GPS verilerini kullanarak konum bilgi üretmek için gereklidir.": "Required to generate location info using GPS data.",
  "GPS verilerini kullanarak konum bilgisi üretmek için gereklidir.": "Required to generate location information using GPS data.",
  "Dosya Erişimi": "File Access",
  "Uygulama verilerini aktarmak için gereklidir. Verileriniz sadece yerel cihazınızda depolanır.": "Required to export app data. Your data is stored only on your local device.",
  "İnternet Erişimi": "Internet Access",
  "Uydu görüntüsü altlıklarının yüklenebilmesi için gereklidir.": "Required to load satellite imagery base maps.",

  "== GPS CAPTURE & MODES ==": "",
  "Klasör Seçimi": "Folder Selection",
  "Nokta Seçimi": "Point Selection",
  "Açıklama": "Description",
  "Ölçüm Modu": "Measurement Mode",
  "Örnekleme Süresi": "Sampling Duration",
  "Gürültü Analizi": "Noise Analysis",
  "Konum Bilgisi Alınıyor": "Retrieving Location Info",
  "Sinyal Kalitesi": "Signal Quality",
  "ÖLÇÜM MODU": "MEASUREMENT MODE",
  "Hassas Konum Belirleme": "Precise Positioning",
  "Hızlı Konum Belirleme": "Fast Positioning",
  "Ölçüm Noktası Bilgileri": "Measurement Point Info",
  "Klasör Adı": "Folder Name",
  "Nokta Adı": "Point Name",
  "Açıklama (Opsiyonel)": "Description (Optional)",
  "ÖLÇÜMÜ BAŞLAT": "START SURVEY",
  "İPTAL": "CANCEL",
  "Klasör": "Folder",
  "Nokta": "Point",
  "Hassasiyet Limitini Aş": "Exceed Accuracy Limit",
  "Hassasiyet Sınırı": "Accuracy Limit",
  "Metre": "Meter",
  "Ölçüm Süresi": "Measurement Duration",
  "Saniye": "Seconds",
  "SESLİ / SÖZLÜ YARDIM": "VOICE FEEDBACK",
  "TİTREŞİM GERİ BİLDİRİMİ": "VIBRATION FEEDBACK",
  "ÖLÇÜM PARAMETRELERİ": "MEASUREMENT PARAMETERS",
  "Maksimum Hassasiyet Sınırı": "Maximum Accuracy Limit",
  "Saniyede bir örnek ver toplanmıştır. Alınan örneklerin aritmetik ortalaması ve istatistiksel hata analizleri hesaplanarak nihai hassasiyet değeri türetilmiştir.": "Sample data was collected every second. The arithmetic mean of the samples and statistical error analysis were calculated to derive the final precision value.",
  "Detaylı Raporu": "Detailed Report",
  "Veriyi Kaydet": "Save Data",
  "Kayıt Tamamlandı": "Record Completed",
  "Zaman": "Time",
  "Enlem": "Latitude",
  "Boylam": "Longitude",
  "Toplam Süre": "Total Duration",
  "Analiz Edilen Örnek": "Analyzed Samples",
  "Filtrelenen Örnek": "Filtered Samples",
  "Doğruluk Sınırı": "Accuracy Limit",
  "Durum": "Status",
  "Ölçüm Yapılıyor": "Measuring",
  "Numuneler Toplanıyor": "Collecting Samples",
  "Süre": "Duration",
  "Ölçümü Kaydet": "Save Measurement",
  "Ölçüm Tamamlandı": "Measurement Completed",
  "Dil Seçin": "Select Language",
  "DİL AYARLARI UYGULANIYOR": "APPLYING LANGUAGE SETTINGS",
  "Sinyal Bekleniyor": "Waiting for Signal",
  "Limiti (m)": "Limit (m)",
  "Süresi (sn)": "Duration (sec)",
  "DÜŞÜK SİNYAL KALİTESİ": "LOW SIGNAL QUALITY",
  "YETERSİZ KONUM VERİSİ": "INSUFFICIENT POSITION DATA",
  "ORTA SİNYAL KALİTESİ": "MEDIUM SIGNAL QUALITY",
  "GÜÇLÜ SİNYAL KALİTESİ": "STRONG SIGNAL QUALITY",
  "Ölçüm sırasında çevresel ve donanımsal faktörler nedeniyle hatalar tespit edildi, ölçümün açık bir alanda tekrarlanması önerilir!": "Errors detected due to environmental & hardware factors. Repeating in open areas is recommended!",
  "Ölçüm sırasında çevresel veya donanımsal faktörler nedeniyle yeterli sayıda konum verisi toplanamadı, ölçüm süresinin uzatılması önerilir!": "Insufficient samples collected due to environmental/hardware factors. Extending duration is recommended!",
  "Toplanan veriler hassasiyet limitlerine uygun görünüyor.": "Collected data appears to be within accuracy limits.",
  "Hassasiyet Bekleniyor...": "Waiting for Accuracy...",
  "Mevcut hassasiyet": "Current accuracy",
  "belirlenen": "is higher than defined",
  "limitinden yüksek.": "limit.",
  "Uydu Kilidi Bekleniyor...": "Waiting for Satellite Lock...",
  "Sadece GNSS modu aktif.": "Only GNSS mode active.",
  "Yükseklik verisi içeren uydu sinyali bekleniyor.": "Satellite signal with altitude data is awaited.",
  "KONUM ÖRNEĞİ": "LOCATION SAMPLES",
  "SABİT TUTUN": "KEEP DEVICE STILL",
  "Hemen Bitir ve Kaydet": "Finish and Save Now",
  "Onaylanan": "Approved",
  "Aykırı Değer": "Outliers",
  "Hız Filtresi": "SpeedFilt",
  "Çoklu Oturum (Multi-Session)": "Multi-Session Mode",
  "Çoklu Oturum": "Multi-Session",
  "Koordinat Dönüşümü": "Coordinate Conversion",
  "Uzun süreli ölçümlerde (30, 60 ve 90 sn) birikimli GPS kaymalarını sıfırlamak ve en kaliteli uydu verisini yakalamak için geliştirilen akıllı ölçüm modudur:": "An intelligent measurement mode developed to reset cumulative GPS drift during long measurements (30, 60 and 90s) and capture high-quality geo-data:",
  "Uzun süreli ölçümlerde (30sn, 60sn ve 90sn) multipath etkilerini tespit etmek ve en kaliteli uydu verisini yakalamak için geliştirilen akıllı ölçüm modudur:": "An advanced multi-epoch observation scheme engineered for extended static surveys (30s, 60s, and 90s) designed to identify multipath reflections and isolate high-quality GNSS observables:",
  "<b>Donanım Sıfırlama:</b> Her 15 saniyelik ölçüm periyodunun ardından ölçüm (iOS için 30, Android için 15 saniye) otomatik olarak duraklatılır ve cihazın GPS alıcısı arka planda tamamen yeniden başlatılır.": "<b>Hardware Reset:</b> After each 15-second measurement period, the session is paused (30 seconds for iOS, 15 seconds for Android) and the device's GPS receiver is fully restarted in the background.",
  "<b>Donanım Sıfırlama:</b> Her 15 saniyelik ölçüm periyodunun ardından ölçüm otomatik olarak duraklatılır ve cihazın GPS/GNSS alıcısı arka planda tamamen yeniden başlatılır.": "<b>Hardware Reset:</b> At the end of each completed 15-second epoch window, observation is micro-paused to programmatically force-restart the hardware GPS/GNSS receiver subsystem, resolving carrier phase state biases.",
  "<b>Yeniden Kilitlenme:</b> Verilen bu arada cihazın uydulara daha temiz açılardan yeniden kilitlenmesi sağlanır; böylece multipath (sinyal yansıması) etkisi en aza indirilir.": "<b>Re-locking:</b> During this interval, the device is allowed to lock onto satellites cleanly, minimizing multipath (signal reflection) effects.",
  "<b>Yüksek Doğruluk:</b> Farklı zaman dilimlerinde sıfırlanıp tekrar alınan temiz örneklerin birleştirilmesiyle, tekil ve uzun bir ölçüme kıyasla çok daha kararlı ve hassas koordinatlar elde edilir.": "<b>High Accuracy:</b> By combining clean samples taken at different intervals, significantly more stable and precise coordinates are obtained compared to a single long measurement.",
  "Çoklu Oturum (Multi-Session) devam ediyor, lütfen bekleyiniz...": "Multi-Session is active, please wait...",
  "GPS Yeniden Başlatılıyor": "Restarting GPS",
  "Safari Ayarlarından \"Konum\" İznini Kontrol Edin": "Check \"Location\" Permission under Safari Settings",
  "Uygula": "Apply",
  "Yeni Proje Oluştur": "Create New Project",
  "Mevcut Proje Seç": "Select Existing Project",
  "Proje Bilgisi": "Project Info",
  "Proje Adı": "Project Name",
  "Örn: Saha Çalışması A": "e.g.: Field Study A",
  "Seçiniz...": "Select...",
  "Koordinat Sistemi": "Coordinate System",
  "WGS84 (Enlem-Boylam)": "WGS84 (Lat-Lng)",
  " (Enlem-Boylam)": " (Lat-Lng)",
  "ITRF96 - 3° - TM": "ITRF96 - 3° - TM",
  "ITRF96 - 6° - UTM": "ITRF96 - 6° - UTM",
  "ED50 - 3° - TM": "ED50 - 3° - TM",
  "ED50 - 6° - UTM": "ED50 - 6° - UTM",
  "ÖLÇÜME HAZIRLAN": "PREPARE FOR SURVEY",
  "Konum izni reddedildi. Lütfen ayarlardan izin verin.": "Location permission denied. Please allow it in settings.",
  "Konum alınamıyor. GPS sinyali zayıf olabilir.": "Location cannot be retrieved. GPS signal might be weak.",
  "Zaman aşımı. GPS yanıt vermedi.": "Timeout. GPS did not respond.",
  "Tarayıcınız konum servisini desteklemiyor.": "Your browser does not support location services.",
  "Nokta İsmi": "Point Name",
  "Nokta1": "Point1",
  "5sn": "5s",
  "5sn (Hızlı)": "5s (Rapid)",
  "10sn": "10s",
  "10sn (Hızlı)": "10s (Rapid)",
  "15sn": "15s",
  "15sn (Hızlı)": "15s (Rapid)",
  "30sn": "30s",
  "60sn": "60s",
  "90sn": "90s",
  "120sn": "120s",
  "15s x 2oturum": "15s x 2sessions",
  "15s x 4oturum": "15s x 4sessions",
  "15s x 6oturum": "15s x 6sessions",
  "90sn (Oturumsuz)": "90s (No Session)",
  "Hassasiyet": "Accuracy",
  "Kalan Süre": "Remaining Time",
  "Ölçüm": "Measurement",
  "Konum verisi alınamadı.": "Location data could not be retrieved.",

  "== SUMMARY CARD & ANALYSIS ==": "",
  "GÜVENLİ": "RELIABLE",
  "ORTA LIGHT": "MODERATE",
  "ORTA": "Medium",
  "Orta": "Medium",
  "ORTA GÜVEN": "MEDIUM RELIABILITY",
  "GÜVENSİZ": "UNRELIABLE",
  "VERİ AZ": "LOW DATA",
  "YÜKSEKLİK": "HEIGHT",
  "UYARI": "WARNING",
  "ÖLÇÜM DETAYLARI": "MEASUREMENT DETAILS",
  "Yatay Sapma": "Horizontal Deviation",
  "Düşey Sapma": "Vertical Deviation",
  "Aritmetik Ortalama": "Arithmetic Mean",
  "Ağırlıklı Dengeleme": "Weighted Least Squares",
  "Ağırlıklı En Küçük Kareler": "Weighted Least Squares",
  "HYBRID_v1": "HYBRID_v1",
  "Hibrit Yöntem (HYBRID_v1)": "Hybrid Method (HYBRID_v1)",
  "Yatay Hata": "Horizontal Error",
  "KESİN KOORDİNAT (REFERANS)": "PRECISE COORDINATE (REFERENCE)",
  "Nirengi Noktası (Referans)": "Triangulation Point (Reference)",
  "HAM VERİ": "RAW DATA",
  "KESİN NOKTA (REF)": "PRECISE POINT (REF)",
  "Ham Ölçümler": "Raw Measurements",
  "Küme": "Cluster",
  "nokta": "points",
  "Sapma": "Deviation",
  "Lejant": "Legend",
  "En Düşük Sinyal Gücü": "Lowest Signal Strength",
  "En Yüksek Sinyal Gücü": "Highest Signal Strength",
  "Açık": "On",
  "Kapalı": "Off",
  "Yarım": "Partial",
  "Tamam": "OK",
  "Haritayı Kapat": "Close Map",
  "Haritada Göster": "Show on Map",
  "Haritada İzle": "Track on Map",
  "Gerçek Zamanlı Veri Gözlemi": "Real-Time Data Observation",
  "Canlı Veri Haritası": "Live Data Map",
  "Filtrelenmiş Örnekler": "Filtered Samples",
  "Tüm Ham Gözlemler (Raw)": "All Raw Observations",
  "YENİ NOKTA EKLE": "ADD NEW POINT",
  "ÖLÇÜMÜ BİTİR": "FINISH SURVEY",
  "Yeni Nokta Ekle": "Add New Point",
  "Ölçümü Bitir": "Finish Survey",

  "== SAVED LOCATIONS LIST ==": "",
  "Kayıtlı ölçüm bulunamadı.": "No saved measurements found.",
  "Klasörü Sil": "Delete Folder",
  "Klasörü Yeniden Adlandır": "Rename Folder",
  "Noktayı Sil": "Delete Point",
  "Yeni Klasör Adı": "New Folder Name",
  "Yeni Nokta Adı": "New Point Name",
  "Hepsini Seç": "Select All",
  "Seçilenleri Sil": "Delete Selected",
  "Sil": "Delete",
  "Vazgeç": "Cancel",
  "Ara...": "Search...",
  "Klasörler": "Folders",
  "Tüm Ölçümler": "All Measurements",
  "Öğeler": "Items",
  "Detayları Gizle": "Hide Details",
  "Koordinatları Gör": "View Coordinates",
  "SİL": "DELETE",
  "Noktayı Düzenle": "Edit Point",
  "GPS Sinyali": "GPS Signal",
  "Harita Üzerinde Gör": "View on Map",
  "Navigasyona Gönder": "Send to Navigation",
  "Karışık": "Mixed",
  "Projeyi Düzenle": "Edit Project",
  "Projeyi Sil": "Delete Project",
  "Henüz Proje Yok": "No Projects Yet",
  "Yeni bir ölçüm yaparak başlayabilirsiniz.": "You can start by making a new measurement.",

  "== DATA EXPORT SCREEN ==": "",
  "Format Seçimi": "Format Selection",
  "Farklı formatlarda kayıtlı noktalarınızı dışa aktarın.": "Export your saved points in different formats.",
  "Unified format (Excel/TXT)": "Unified format (Excel/TXT)",
  "KML (Google Earth) format": "KML (Google Earth) format",
  "Excel Dışa Aktar": "Export to Excel",
  "TXT Dışa Aktar": "Export to TXT",
  "KML Dışa Aktar": "Export to KML",
  "Dışa Aktarılacak Ölçüm Seçin": "Select Measurements to Export",
  "Tüm Klasörler": "All Folders",
  "Kayıtlı ölçüm bulunmuyor.": "No saved measurements available.",
  "Kayıtlı Proje Bulunamadı": "No Saved Projects Found",
  "Excel Dökümanı (.XLSX)": "Excel Document (.XLSX)",
  "Metin Belgesi (.TXT)": "Text File (.TXT)",
  "ACB - LABS": "ACB - Labs",
  "Hassas Analiz & ACB - Labs": "Precision Analysis & ACB - Labs",
  "Analiz sayfasına giriş için şifreyi giriniz:": "Enter password to access analysis page:",
  "Hatalı şifre!": "Incorrect password!",
  "Aktivasyon Kodu": "Activation Code",
  "Giriş Yap": "Login",
  "EKSEN KAYDIRMA (OFFSET NAVİGASYON)": "AXIS SHIFT (OFFSET NAVIGATION)",
  "Yukarı Kaydır (Y +1m)": "Shift Up (Y +1m)",
  "Aşağı Kaydır (Y -1m)": "Shift Down (Y -1m)",
  "Sola Kaydır (X -1m)": "Shift Left (X -1m)",
  "Sağa Kaydır (X +1m)": "Shift Right (X +1m)",
  "Eksenleri Sıfırla": "Reset Axes",
  "SIFIRLA": "RESET",
  "Kesin Koordinat (Referans Merkez)": "Precise Coordinates (Reference Center)",
  "Kesin Koordinat": "Precise Coordinates",
  "Ham Uydu Noktaları": "Raw Satellite Points",
  "Kayıtlı koordinat bulundu ve yüklendi!": "Saved coordinate found and loaded!",
  "Hafızayı Temizle": "Clear Memory",
  "TEMİZLE": "CLEAR",

  "== STAKEOUT MODULE (APLİKASYON) ==": "",
  "Aplikasyon Noktası Seçin": "Select Stakeout Point",
  "Haritada Dokunarak veya Listeden Nokta Belirleyin": "Identify Point by Clicking on Map or List",
  "Nokta Seç": "Select Point",
  "Kayıtlı Noktalardan Seç": "Select from Saved Points",
  "Manuel Koordinat Gir": "Enter Coordinat Manually",
  "Aplikasyona Başla": "Start Stakeout",
  "Mesafe": "Distance",
  "Açısı": "Angle",
  "Yön": "Direction",
  "Kuzey": "North",
  "Güney": "South",
  "Doğu": "East",
  "Batı": "West",
  "İleri": "Forward",
  "Geriye": "Backward",
  "Sola": "Left",
  "Sağa": "Right",
  "Aplikasyon Noktasına Ulaşıldı!": "Stakeout Point Reached!",
  "Sapma Değerleri": "Deviation Values",
  "Mevcut Konum": "Current Location",
  "Hedef Konum": "Target Location",
  "Nokta Ekle": "Add Point",
  "Hedef Değerler": "Target Values",
  "GİT": "GO",
  "Köşe": "Vertex",
  "nokta ve": "point and",
  "geometri yüklendi": "geometries loaded",
  "KML dosyaları içerisinde veri bulunamadı.": "No data found in KML files.",
  "KMZ dosyası içerisinde KML bulunamadı.": "KML not found inside KMZ file.",
  "KMZ okuma hatası:": "KMZ read error:",
  "KMZ dosyası okunamadı.": "KMZ can not be read.",
  "KML/KMZ dosya yüklendi": "KML/KMZ file loaded",
  "Geçersiz koordinat girişi.": "Invalid coordinate input.",
  "Tüm Noktalar": "All Points",
  "Aplikasyon Ekranı": "Stakeout Screen",
  "Hata": "Error",
  "Bilgi": "Info",
  "Başarılı": "Success",
  "El ile Giriş": "Manual Input",
  "KML / KMZ Yükle": "Load KML / KMZ",
  "Nokta Listesini Gör": "View Point List",
  "Nokta Hazır": "Points Ready",
  "Haritada gösterilecek veri bulunamadı.": "No data found to show on map.",
  "Liste Boş": "List is Empty",
  "EMİN MİSİNİZ? (TEKRAR TIKLAYIN)": "ARE YOU SURE? (CLICK AGAIN)",
  "LİSTEYİ TEMİZLE": "CLEAR LIST",
  "Örn: P1": "e.g.: P1",
  "Enlem (N/X)": "Latitude (N/X)",
  "Sağa (E/Y)": "Easting (E/Y)",
  "Boylam (E/Y)": "Longitude (E/Y)",
  "Yukarı (N/X)": "Northing (N/X)",
  "LİSTEYE EKLE": "ADD TO LIST",
  "EMİN MİSİNİZ?": "ARE YOU SURE?",
  "EKRANI TEMİZLE": "CLEAR SCREEN",
  "YAKIN ÇEKİM MODU": "CLOSE RECONCILIATION MODE",
  "HEDEFE ULAŞILDI": "TARGET REACHED",
  "Seçili Nokta": "Selected Point",
  "İLERİ / GERİ": "FORWARD / BACKWARD",
  "KUZEY / GÜNEY": "NORTH / SOUTH",
  "SAĞ / SOL": "RIGHT / LEFT",
  "DOĞU / BATI": "EAST / WEST",
  "İLERİ": "FORWARD",
  "KUZEY": "NORTH",
  "GERİ": "BACKWARD",
  "GÜNEY": "SOUTH",
  "SAĞ": "RIGHT",
  "DOĞU": "EAST",
  "SOL": "LEFT",
  "BATI": "WEST",
  "Nokta Listesi": "Point List",
  "Manuel Ekle": "Add Manually",
  "Manuel Koordinat Ekle": "Add Coordinate Manually",
  "Dosyadan Aktar": "Import from File",
  "Navigasyon": "Navigation",
  "Pusula verisi bekleniyor... (K/G/D/B modu)": "Waiting for compass data... (N/S/E/W mode)",
  "UTM Zon (6°)": "UTM Zone (6°)",
  "Dilim Orta Meridyeni (DOM)": "Central Meridian (CM)",
  "Geometri": "Geometry",

  "== DATA ANALYSIS VIEW (R&D) ==": "",
  "Teknik raporu indirmek için şifreyi giriniz:": "Enter password to download technical report:",
  "Lütfen kesin koordinatları eksiksiz giriniz.": "Please enter complete precise coordinates.",
  "KESİN NOKTA": "PRECISE POINT",
  "ORTALAMA": "MEAN",
  "Gelişmiş Raporlama Sistemi": "Advanced Reporting System",
  "Güvenilirlik Analizi": "Reliability Analysis",
  "GÜVEN SKORU": "RELIABILITY SCORE",
  "Saçılım": "Spread",
  "Max Saçılım": "Max Spread",
  "Sensör Hass.": "Sensor Accuracy",
  "Örnek Sayısı": "Number of Samples",
  "Örnek Sayısı:": "Number of Samples:",
  "Ağırlıklı En Küçük Kareler (Varsayılan)": "Weighted Least Squares (Default)",
  "PNG İndir (İngilizce)": "Download PNG (English)",
  "DÜŞÜK GÜVENLİ SİNYAL (KIRMIZI)": "LOW RELIABILITY SIGNAL (RED)",
  "Kritik uyarı: Veri saçılımı ekstrem düzeyde. Ölçüm kalitesi güvenli sınırların altında kalmaktadır.": "Critical alert: Data spread is extreme. Measurement quality is below secure thresholds.",
  "Ölçülen veriler sensörün bildirdiği hassasiyete göre daha geniş bir alana yayılmış durumda (Muhtemel Multipath).": "Measured data is spread wider than the sensor-reported accuracy (Likely Multipath).",
  "Analiz Yöntemini Seçin": "Select Analysis Method",
  "Güvenilirlik": "Reliability",
  "Kesin Koordinatlı Analiz": "precise coordinate analysis",
  "İstatistiki Yöntem Analizleri": "Statistical Method Analysis",
  "Koordinatsız Analiz": "Standard Analysis",
  "Veri Saçılımı Grafiği": "Data Scatter Plot",
  "Yöntem Sonuçları Grafiği": "Method Results Graph",
  "Aykırı Değer Tespit Grafiği": "Outlier Detection Graph",
  "Zamana Bağlı Hata Grafiği": "Time-Dependent Error Graph",
  "Zamana Bağlı Hata Grafiği (Time-Dependent Error Graph)": "Time-Dependent Error Graph",
  "Model Açıklamaları": "Model Explanations",
  "Tüm ham ölçümlerin ağırlıksız ortalamasını hesaplar. Veriler homojen olduğunda kararlıdır.": "Calculates unweighted mean of all raw measurements. Stable when data is homogenous.",
  "Ölçüm hassasiyetine (accuracy) göre ters ağırlıklı modelleme yaparak güvensiz verilerin etkisini azaltır.": "Does inverse weight modeling based on measurement accuracy to minimize unsafe data impact.",
  "Ölçüm serisindeki en büyük ve en küçük sınırsal enlemlerin/boylamların ortalamasını alarak geometrik uç merkezini süzgeçten geçirir.": "Averages the maximum and minimum spatial latitudes/longitudes in the survey series to filter the geometric outlier center.",
  "K-Means (4 Küme)": "K-Means (4 Clusters)",
  "Ham konum verilerini mekansal yakınlıklarına göre 4 temel kümeye segmentler, en kararlı ve yoğun kümenin ağırlıklı merkezini alır.": "Segments raw location data into 4 core clusters based on spatial proximity, then computes the weighted mean of the most stable and dense cluster.",
  "Hodges-Lehmann Eleme": "Hodges-Lehmann Selection",
  "Jeodezik Hodges-Lehmann testi ile uyuşumsuz ve kaba hatalı uç koordinat verilerini sistemden döngüsel olarak temizler.": "Iteratively cleans outlier and coarse errors from the system using geodetic Hodges-Lehmann robust testing.",
  "Veriyi doğrudan K-Means (k = 4) ile gruplar. Her kümede bağımsız iç Hodges-Lehmann testi yapıp en yoğun grubu seçer ve nihai konumu ağırlıklı en küçük kareler (WLS) ile dengeler.": "Groups data via K-Means (k=4) directly. Performs independent internal Hodges-Lehmann test within each cluster to pick the most dense group, and optimizes the final location via Weighted Least Squares (WLS).",
  "Proje ve Nokta Seçimi": "Project and Point Selection",
  "Proje Seçin": "Select Project",
  "Proje Seçiniz...": "Select Project...",
  "Nokta Seçin": "Select Point",
  "Nokta Seçiniz...": "Select Point...",
  "Kesin Koordinat Girişi (": "Precise Coordinate Input (",
  "Sağa (Y)": "Easting (Y)",
  "Enlem (Lat)": "Latitude (Lat)",
  "Yukarı (X)": "Northing (X)",
  "Boylam (Lng)": "Longitude (Lng)",
  "Analizi Gerçekleştir": "Execute Analysis",
  "İstatistikleri Göster": "Show Statistics",
  "Analizi Başlat": "Execute Analysis",
  "SÜZGEÇ YÖNTEMİ:": "FILTER METHOD:",
  "SÜZGEÇ YÖNTEMİ": "FILTER METHOD",
  "Analiz Sonuçları": "Analysis Results",
  "Analiz Sonuçlarını Haritada Gör": "View Analysis Results on Map",
  "Yöntem": "Method",
  "Katılan Veri": "Used Points",
  "ΔDüşey (m)": "ΔVertical (m)",
  "EN İYİ": "BEST",
  "Hesaplanan Y (Sağa)": "Calculated Y (Easting)",
  "Hesaplanan Enlem (Lat)": "Calculated Lat",
  "Hesaplanan X (Yukarı)": "Calculated X (Northing)",
  "Hesaplanan Boylam (Lng)": "Calculated Lng",
  "Hassasiyet Analiz Paftası": "Accuracy Analysis Plot",
  "HARİTA PAFTASI AYARLARI": "MAP PLOT SETTINGS",
  "Eksen:": "Axis:",
  "Eksen Limiti:": "Axis Limit:",
  "Otomatik": "Auto",
  "Kılavuz Adımı:": "Grid Step:",
  "Yazı Boyutu:": "Font Size:",
  "Nokta Boyutu:": "Point Size:",
  "Eksen Limit:": "Axis Limit:",
  "Hata Limiti:": "Error Limit:",
  "Süre Limiti:": "Duration Limit:",
  "Auto (En az 10m)": "Auto (Min 10m)",
  "ZAMAN SERİSİ GRAFİK AYARLARI": "TIME SERIES CHART SETTINGS",
  "Veri Saçılımı Grafik Ayarları": "DATA DISPERSION CHART SETTINGS",
  "İstatistiki Ölçüm Raporu": "Statistical Measurement Report",
  "Nokta:": "Point:",
  "Ham Ölçüm (Güvenilir)": "Raw Measurement (Reliable)",
  "Hass:": "Acc:",
  "h-ELİPSOİD (Z)": "h-ELLIPSOID (Z)",
  "Alt (H)": "Alt (H)",
  "ΔYatay (m)": "ΔHz (m)",
  "DURUM": "STATUS",
  "Kümeleme Analiz Özeti": "Clustering Analysis Summary",
  "Zamana Bağlı Yukarı (X)": "Time-Based Northing (X)",
  "Zamana Bağlı Sağa (Y)": "Time-Based Easting (Y)",
  "Zamana Bağlı Sistematik Yatay Hata (ΔHz)": "Time-Based Systematic Horiz. Error (ΔHz)",
  "* Her bir ölçüm noktasının kesin koordinata olan mesafesinin zamanla değişimi": "* The change of distance of each sample point to precise coordinate over time",
  "GPS_Plus_TEKNIK_RAPOR İndir": "Download GPS_Plus_TECHNICAL_REPORT",
  "Yatayda En Başarılı Algoritma": "Most Successful Horiz. Algorithm",
  "Kesin Koordinatlı Analiz Raporu": "Precise Coordinates Analysis Report",
  "Normal Ölçüm Raporu Al": "Get Normal Measurement Report",
  "Ölçüm Raporu": "Survey Report",
  "* Bu testler Android/iOS sensör verileri ile kesin koordinatlar arasındaki sistematik hatayı analiz etmek içindir.": "* These tests are designed to analyze systematic error between iOS/Android sensor data and precise coordinates.",

  "== SETTINGS VIEW (AYARLAR) ==": "",
  "Veri Tabanı Yedekleme": "Database Backup & Restore",
  "Verilerinizi yedekleyebilir veya yedekten geri yükleyebilirsiniz.": "You can back up your data or restore from a backup.",
  "Yedek Al": "Backup Data",
  "Yedek Yükle": "Restore Data",
  "Yedek başarıyla oluşturuldu ve indirildi.": "Backup created and downloaded successfully.",
  "Geçersiz yedek dosyası formatı.": "Invalid backup file format.",
  "Yedek dosyasındaki ölçümler, mevcut verilerinizin üzerine eklenecek ve aynı isimdeki projeler otomatik olarak yeni isimle kaydedilecektir. Devam etmek istiyor musunuz?": "The measurements in the backup file will be appended to your current data, and projects with the same name will be automatically saved under new names. Do you want to continue?",
  "Yedek başarıyla yüklendi. Değişikliklerin uygulanması için uygulama yenilenecektir.": "Backup restored successfully. The application will reload to apply changes.",
  "Yedek oluşturulurken bir hata oluştu: ": "An error occurred while creating backup: ",
  "Yedek yüklenirken bir hata oluştu: ": "An error occurred while restoring backup: ",
  "Geçersiz yedek dosyası: ": "Invalid backup file: ",
  "Hesaplama Yöntemi": "Calculation Method",
  "Harita Sağlayıcısı": "Map Provider",
  "Sesli Bildirim": "Voice Notification",
  "metre": "meters",
  "saniye": "seconds",
  "Google Hibrit": "Google Hybrid",
  "Google Satellite": "Google Satellite",
  "OpenTopoMap": "OpenTopoMap",
  "1-Google Hibrit": "1-Google Hybrid",
  "2-Google Satellite": "2-Google Satellite",
  "3-Open Topo Map": "3-Open Topo Map",
  "4-Esri World Imagery": "4-Esri World Imagery",
  "5-Bing Satellite": "5-Bing Satellite",
  "Esri World Imagery (ArcGIS Satellite Services)": "Esri World Imagery (ArcGIS Satellite Services)",
  "Bing Satellite Maps (Microsoft Virtual Earth)": "Bing Satellite Maps (Microsoft Virtual Earth)",
  "Bing Satellite": "Bing Satellite",
  "Tüm ayarlar fabrika ayarlarına sıfırlanacak. Emin misiniz?": "All settings will be reset to factory defaults. Are you sure?",
  "Ayarlar başarıyla sıfırlandı.": "Settings successfully reset.",
  "Sunucuya erişilemedi": "Could not access server.",
  "Yeni Sürüm Mevcut": "New Version Available",
  "Uygulama Güncel": "Application Up to Date",
  "Hata Oluştu": "Error Occurred",
  "Güncelleştirme denetimi sırasında bir hata oluştu. Lütfen internet bağlantınızı kontrol edin.": "An error occurred during update check. Please check your internet connection.",
  "Güncelleştirme Denetimi": "Check for Updates",
  "Denetleniyor...": "Checking...",
  "Ölçüm Ayarları": "Measurement Settings",
  "Wi-Fi / Şebeke Verilerini Filtrele": "Filter Wi-Fi / Cellular Data",
  "1. Ağırlıklı En Küçük Kareler": "1. Weighted Least Squares",
  "2. MAD + DBSCAN": "2. MAD + DBSCAN",
  "2. DB SCAN (MAD + DBSCAN)": "2. DB SCAN (MAD + DBSCAN)",
  "2. K-Means Kümeleme": "2. K-Means Clustering",
  "3. Huber M-Kestiricisi": "3. Huber M-Estimator",
  "4. Hampel M-Kestiricisi": "4. Hampel M-Estimator",
  "5. Hodges-Lehmann R-Kestiricisi": "5. Hodges-Lehmann R-Estimator",
  "6. Tukey's Trimean L-Kestiricisi": "6. Tukey's Trimean L-Estimator",
  "7. Optimal S-Kestiricisi": "7. Optimal S-Estimator",
  "GÜRBÜZ / ROBUST": "ROBUST",
  "AMİRAL GEMİSİ / HİBRİT": "FLAGSHIP / HYBRID",
  "Aktif edildiğinde, sadece yükseklik verisi içeren uydu tabanlı konumlar ölçüme dahil edilir. Açık alanlarda hassasiyeti artırır.": "When enabled, only satellite-based positions with altitude data are included in measurements. Increases accuracy in open areas.",
  "Birim ve Duyarlılık": "Unit and Precision",
  "Konum (Virgülden sonraki duyarlılık)": "Location (Decimal precision)",
  "WGS84 harici koordinat sistemlerinde geçerlidir.": "Applicable to coordinate systems other than WGS84.",
  "Yükseklik (Virgülden sonraki duyarlılık)": "Elevation (Decimal precision)",
  "Yükseklik Tipi": "Elevation Type",
  "Ortometrik Yükseklik": "Orthometric Elevation",
  "Elipsoidal Yükseklik": "Ellipsoidal Elevation",
  "Görünüm & Bildirim": "Appearance & Feedback",
  "Ölçüm Sırasında": "During Measurement",
  "Titreşimli Bildirim": "Vibrational Notifications",
  "Ekran Her Zaman Açık": "Keep Screen Always On",
  "Ölçüm ve Aplikasyon Sırasında": "During Measurement and Stakeout",
  "Onboarding Ekranı": "Onboarding Screen",
  "Her açılışta göster": "Show on every startup",
  "Ayarları Sıfırla": "Reset Settings",
  "KOORDİNAT SİSTEMİ": "COORDINATE SYSTEM",
  "Varsayılan": "Default",
  "HASSASİYET VE ÖLÇÜM": "ACCURACY AND MEASUREMENT",
  "Limit Değeri": "Limit Value",
  "Ölçüm Örkemele Süresi": "Measurement Sampling Duration",
  "UÇBİLGİ VE GERİBİLDİRİM": "NOTIFICATIONS AND FEEDBACK",
  "Sesli bildirimleri ve titreşim geri bildirimlerini etkinleştirin.": "Enable sound alerts and vibration feedback.",
  "Ondalık Hassasiyetleri": "Decimal Precision Settings",
  "Ekranı Açık Tut": "Keep Screen On",
  "Sıkça Sorulan Sorular": "Frequently Asked Questions",
  "Harita": "Map",
  "Genel": "General",
  "Ölçüm Tipi": "Measurement Type",
  "Yükseklik Türü": "Height Type",
  "Yalnızca GNSS (GPS)": "GNSS (GPS) Only",
  "Onboarding Ekranını Her Seferinde Göster": "Show Onboarding Screen every time",
  "HARİTADA GÖR": "SHOW ON MAP",
  "NAVİGASYONA GÖNDER": "SEND TO NAVIGATION",
  "Düşük Sinyal Kalitesi!": "Low Signal Quality!",
  "Orta Sinyal Kalitesi!": "Medium Signal Quality!",
  "Ölçüm sırasında çevresel ve donanımsal faktörler nedeniyle hatalar tespit edildi.": "Errors were detected during measurement due to environmental and hardware factors.",
  "Gerçek konumunuz gösterilenden farklı olabilir. Ölçümü gökyüzü açık bir alanda tekrarlamanız önerilir.": "Your actual location may differ from what is shown. It is highly recommended to repeat the measurement in an open sky area.",
  "h-ELİPSOİD": "h-ELLIPSOID",
  "ANLADIM": "UNDERSTOOD",
  "Değişiklikleri Kaydet": "Save Changes",
  "Sistem": "System",
  "Hassasiyet Limiti": "Accuracy Limit",
  "Sadece GNSS Modu": "GNSS Only Mode",
  "Hane": "Digits",
  "Yükseklik Duyarlılığı": "Elevation Precision",
  "Yükseklik Görünümü": "Elevation Mode",
  "Harita Kaynağı": "Map Base Layer",
  "Sesli Rehberlik": "Voice Guidance",
  "Titreşimli Geri Bildirim": "Haptic Feedback",
  "Ölçüm ve Aplikasyonda Ekran Arazide Açık Kalsın": "Keep Screen On During Measurement & Stakeout",
  "Ayarları Fabrika Ayarlarına Sıfırla": "Reset All Settings to Factory Defaults",

  "== HELP VIEW (YARDIM) ==": "",
  "Yardım & Hakkında": "Help & About",
  "Nasıl Kullanılır?": "How It Works?",
  "Aplikasyon (Arazide Nokta Bulma)": "Stakeout (Finding Points in Field)",
  "Sinyal Güvenilirlik Analizi": "Signal Reliability Analysis",
  "Veri sınırları üzerinden tarafsız referans merkez noktası belirlenir.": "Identifies a neutral bounding region to establish an initial anchor.",
  "Referans noktasına ortalama donanımsal hassasiyetten daha uzak noktalar elenir.": "Outliers further than the average hardware error are rejected.",
  "Temizlenmiş veri 4 bağımsız yoğunluk kümesine bölünür.": "Clusters the cleaned spatial database into 4 high-density bins.",
  "Her küme kendi içinde ağırlıklı dengeleme ile tek bir noktaya dönüştürürlür.": "Solves a Least Squares estimate for each cluster.",
  "Her küme kendi içinde ağırlıklı dengeleme ile tek bir noktaya dönüştürülür.": "Each cluster is reduced to a single point via weighted least squares adjustment internally.",
  "4 özet nokta arasında uyuşmazlık denetimi yapılarak sonuç konum hesaplanır.": "Conducts a statistical reliability search to locate multi-path errors to compute the final position.",
  "4 özet nokta arasında uyuşmazlık denetimi yapılarak sonuç konum hesaplayan hibrit bir modeldir.": "A hybrid model that performs reliability analysis on the 4 summarized points to calculate the final position.",
  "Ortometrik yükseklik (H), GPS'ten alınan Elipsoid yüksekliğinden (h), TG-20 Jeoid Modeli ondülasyon değeri (N) çıkarılarak hesaplanır.": "Orthometric elevations (H) are solved by subtracting localized geoid heights (N) from the ellipsoidal height (h), mapped from TG-20/EGM96 5'x5' models.",
  "Ortometrik yükseklik (H), ham verilerde bulunan Elipsoid yüksekliğinden (h), TG-20 Jeoid Modeli ondülasyon değeri (N) çıkarılarak hesaplanır.": "Orthometric height (H) is derived relative to the national vertical datum by subtracting the geoid undulation value (N) computed via the TG-20 national geoid model from the raw ellipsoidal height (h).",
  "UYARI / ÖNEMLİ KOŞUL:": "WARNING / IMPORTANT CONDITION:",
  "GEOMETRİK": "GEOMETRIC",
  "KÜMELEME": "CLUSTERING",
  "İSTATİSTİK": "STATISTICS",
  "HİBRİT": "HYBRID",
  "Filtre": "Filter",
  "Ağırlıklı Özet": "Weighted Summary",
  "Hodges-Lehmann Testi": "Hodges-Lehmann Test",
  "Hassasiyet İpuçları": "Accuracy Tips",
  "Hassasiyet Hesabı": "Accuracy Calculation",
  "Konum Hesabı": "Location Calculation",
  "Koordinat Dönüşüm Altyapısı": "Coordinate Conversion Infrastructure",
  "Veri Güvenliği": "Data Security",
  "Veri Kaynakları": "Data Sources",
  "Hakkında": "About",
  "Saha çalışmasına başlamak için ana ekrandaki <b>\"Ölçüm Yap\"</b> butonuna tıklayın.": "Click on the <b>\"Survey\"</b> button on the home screen to start your field work.",
  "• <b>Proje Bilgisi:</b> \"Yeni Proje Oluştur\" ile yeni bir isim verebilir veya \"Mevcut Proje Seç\" ile önceki çalışmalarınıza devam edebilirsiniz.": "• <b>Project Info:</b> Name a new project with \"Create New Project\", or continue existing work via \"Select Existing Project\".",
  "• <b>Koordinat Sistemi:</b> WGS84 (Enlem-Boylam), ITRF96 (3° - TM / 6° - UTM) veya ED50 (3° - TM / 6° - UTM) sistemlerinden birini seçin. Proje bir kez oluşturulduğunda sistem değiştirilemez.": "• <b>Coordinate System:</b> Choose from WGS84 (Lat/Lng), ITRF96 (3° TM / 6° UTM), or ED50 (3° TM / 6° UTM). Once a project is created, its system cannot be changed.",
  "• <b>Ölçüm Süreci:</b> \"Ölçümü Başlat\" dediğinizde belirlediğiniz hassasiyette (2-100 m) ve belirlediğiniz sürede (5-90 sn) veri toplama süreci başlatılır. Uygulama bu aşamada konum örneği alarak verilerin ortalamasını hesaplar. En doğru sonuç için cihazı sabit bir zeminde ve açık bir alanda tutun.": "• <b>Measurement Process:</b> When clicking \"Start Survey\", data is collected based on your specified accuracy (2-100m) and duration (5-90s). The app averages sample coordinate inputs. For highest precision, keep your device still and in an open area.",
  "• <b>Ölçüm Süreci:</b> \"Ölçümü Başlat\" dediğinizde belirlediğiniz hassasiyette ve belirlediğiniz sürede veri toplama süreci başlatılır. En doğru sonuç için cihazı sabit bir zeminde ve açık bir alanda tutun. Çoklu oturum seçeneklerini kullanmanız tavsiye edilir.": "• <b>Observation Process:</b> Initiating \"Start Measurement\" launches raw satellite telemetry recording matching your designated threshold parameters and duration. For geodetic excellence, place the receiver on a stable reference point in an unobstructed skyview environment. Multiple observation sessions are highly recommended.",
  "Kayıtlı noktaları arazide fiziksel olarak bulmak için <b>\"Aplikasyon Yap\"</b> modülünü kullanın.": "Use the <b>\"Stake Out\"</b> module to find saved coordinates on the ground.",
  "• <b>Nokta Seçimi:</b> Proje listenizden hedeflediğiniz noktayı seçin.": "• <b>Point Selection:</b> Select your desired target point from your active project folder list.",
  "• <b>Canlı Rehberlik:</b> Ekranın ortasındaki pusula benzeri gösterge size gitmeniz gereken yönü gösterir.": "• <b>Live Guidance:</b> The central compass-like indicator guides you in the direction you need to move.",
  "• <b>Mesafe Takibi:</b> Hedefe olan kuş uçuşu mesafeniz (metre cinsinden) anlık olarak güncellenir. Uygulamanın metre hassasiyetinde çalıştığını unutmayın.": "• <b>Distance Tracking:</b> The direct line-of-sight distance to your target updates in real-time in meters. Note that precision is within mobile hardware limitations.",
  "• <b>Yaklaşma Modu:</b> Hedefe 5 metreden fazla yaklaştığınızda gösterge daha hassas bir \"yakın çekim\" moduna geçer. Mobil cihazların GPS kısıtları nedeniyle 2 metre ve altına ulaştığınızda \"Hedefe Ulaşıldı\" sinyali ve görsel bildirim alırsınız.": "• <b>Proximity Zoom:</b> Once within 5 meters of your target, the system opens a zoomed 'close reconciliation' target layout. Due to GPS limits, reaching <= 2 meters triggers a 'Target Reached' notice & audio/haptic signal.",
  "Tüm saha verilerinizi <b>\"Kayıtlı Ölçümler\"</b> menüsünden yönetebilirsiniz.": "Manage all collected field coordinates under the <b>\"Saved Surveys\"</b> menu.",
  "• <b>Görüntüleme:</b> Noktalarınızı proje klasörleri altında gruplanmış şekilde görün.": "• <b>Grouping:</b> View and browse your measured points catalog sorted neatly inside their respective project directories.",
  "• <b>Detaylar:</b> Bir noktaya tıkladığınızda koordinatlarını, yüksekliğini, hassasiyetini ve harita üzerindeki konumunu görebilirsiniz.": "• <b>Point Details:</b> Tap any point to view its processed coordinate values, elevation, precision status, and map location.",
  "• <b>Düzenleme:</b> Gereksiz noktaları veya tüm proje klasörlerini silebilirsiniz.Projelere yeniden isim verebilirsiniz.": "• <b>Editing:</b> Delete unused points, rename folders/projects, or delete entire folders instantly.",
  "Saha verilerinizi ofis yazılımlarına aktarmak için <b>\"Veri Aktar\"</b> menüsünü kullanın.": "Use the <b>\"Export Data\"</b> menu to export your field data to office software.",
  "• <b>Google Earth (.kml):</b> Noktalarınızı uydu görüntüsü üzerinde görmek için ideal format.": "• <b>Google Earth (.kml):</b> Ideal for displaying point coordinates as overlay placemarks on top of satellite imagery.",
  "• <b>Excel (.xlsx):</b> Nokta adı, koordinatlar (Y, X, Z), hassasiyet ve tarih bilgilerini içeren detaylı tablo.": "• <b>Excel (.xlsx):</b> Full structured table containing names, processed grid coordinates (Y, X, Z), accuracy bounds, and creation times.",
  "• <b>Metin (.txt):</b> Ham veri formatında (Ad, Y, X, Z) hızlı paylaşım.": "• <b>Plain Text (.txt):</b> Light, standardized raw format (Name, Y, X, Z) for easy importing into geodetic CAD solvers.",
  "• <b>Paylaşım:</b> Oluşturulan dosyaları mobil cihazlarınız ile WhatsApp, E-posta veya Bulut sürücülere doğrudan gönderebilirsiniz.": "• <b>Direct Sharing:</b> Send generated documents directly via native sharing channels like Email, WhatsApp, or cloud drives.",
  "<b>Açık Gökyüzü:</b> En iyi sonuçlar için binalardan, ağaçlardan ve metal yapılardan uzak, gökyüzünü doğrudan gören alanlarda ölçüm yapın.": "<b>Open Sky:</b> For ideal satellite reception, stay away from tall buildings, dense tree canopies, and high-voltage grid lines.",
  "<b>Bekleme Süresi:</b> Uygulamayı açtıktan sonra GPS sinyalinin \"oturması\" için yaklaşık 30 saniye beklemek hassasiyeti 2-5 metreye kadar düşürebilir.": "<b>Warm Up Time:</b> Wait about 30 seconds after opening the app to let the GNSS almanac align, which can immediately improve coordinate accuracy from 10m down to 2-3m.",
  "<b>Bekleme Süresi:</b> Uygulamayı açtıktan sonra 10-15sn beklemek hassasiyeti düşürebilir.": "<b>Dwell Time:</b> Waiting 10-15 seconds after app initialization allows the GNSS receiver to stabilize tracking loops, effectively minimizing horizontal dilution of precision (HDOP).",
  "<b>Güç Modu:</b> Cihazınızın \"Düşük Güç Modu\"nda olmaması gerekir, çünkü bu mod GPS güncelleme sıklığını azaltabilir.": "<b>Power Mode:</b> Ensure your mobile device is not running in 'Low Power Mode', which throttles background sensor sampling rates.",
  "<b>Güç Modu:</b> Cihazınızın \"Düşük Güç Modu\"nda olmaması gerekir, çünkü bu mod konum güncelleme sıklığını azaltabilir.": "<b>Power Constraints:</b> Ensure \"Low Power Mode\" is deactivated on the device; conserving battery resource throttles core location subsystem refresh cycles, interrupting systematic spatial sampling.",
  "Uygulama, ekranda gördüğünüz nihai <b>Hassasiyet</b> değerini şu formülle belirler:": "The system dynamically determines the final <b>Accuracy</b> bound shown using this geodetic model:",
  "Uygulama, ekranda gördüğünüz nihai Hassasiyet değerini şu formül ile hesaplar:": "The application computes the final positional uncertainty (Accuracy) displayed on screen utilizing the following rigorous model:",
  "= Max(Veri Saçılımı, Donanımsal Hassasiyet)": "= Max(Sample Spread, Hardware Reported Accuracy)",
  "* Örneğin; sensör 2m hata payı diyorsa ancak ham veriler 6m'ye yayılıyorsa, gerçek hata payınız 6m olarak kabul edilir.": "* Example: If the internal GPS receiver reports 2m accuracy but collected samples are scattered across 6m, the true confidence radius is evaluated as 6m.",
  "Uygulama, ölçüm sırasında sadece sensörden gelen hata payına bakmaz; aynı zamanda toplanan koordinatların birbirine olan mesafesini (Veri Saçılımı) analiz ederek <b>Multipath (Sinyal Yansıması)</b> riskini değerlendirir:": "During data collection, the system doesn't rely solely on hardware-estimated error. It mathematically analyzes the spatial dispersion of all raw coordinates (Data Spread) to estimate <b>Multipath (Signal Interference)</b> risks:",
  "Uygulama, ölçüm sırasında sadece uydudan gelen donanımsal hassasiyet değerine bakmaz; aynı zamanda toplanan koordinatların birbirine olan mesafesini (Veri Saçılımı) analiz ederek Multipath (Sinyal Yansıması) riskini değerlendirir:": "During field observation, the geodetic processing engine analyzes more than raw hardware-reported error bounds; it evaluates the spatial deviation (Sample Dispersion) of collected epochs to actively filter Multipath signal reflection interference:",
  "Güvenilir Veri (Yeşil)": "Reliable Data (Green)",
  "Veriler yüksek tutarlılıktadır.<br/>Donanımsal Hassasiyet &le; 5m,<br/>Veri Saçılımı &le; 5m,<br/>Veri Saçılımı &le; Donanımsal Hassasiyet,<br/>Veri Sayısı &ge; 15": "Highly consistent readings.<br/>Hardware Estimated Error &le; 5m,<br/>Raw Sample Spread &le; 5m,<br/>Sample Spread &le; Hardware Error,<br/>Collected Epochs &ge; 15",
  "Orta Güvenli Veri / Veri Az (Turuncu)": "Moderate Reliability / Sparse Data (Orange)",
  "Veriler orta tutarlılıktadır.<br/>5m &lt; Donanımsal Hassasiyet &le; 20m,<br/>5m &lt; Veri Saçılımı &le; 20m,<br/>Veri Saçılımı &gt; Donanımsal Hassasiyet,<br/>Veri Sayısı &lt; 15": "Sufficient for basic layouts.<br/>5m &lt; Hardware Estimated Error &le; 20m,<br/>5m &lt; Raw Sample Spread &le; 20m,<br/>Sample Spread &gt; Hardware Error,<br/>Collected Epochs &lt; 15",
  "Güvensiz Veri (Kırmızı)": "Unreliable Geodetic Data (Red)",
  "Veriler yüksek oranda sapmalı ve güvensizdir.<br/>Donanımsal Hassasiyet &gt; 20m,<br/>Veri Saçılımı &gt; 20m,<br/>Veri Saçılımı &gt; Donanımsal Hassasiyet x 3": "High risk of geodetic offsets.<br/>Hardware Estimated Error &gt; 20m,<br/>Raw Sample Spread &gt; 20m,<br/>Sample Spread &gt; Hardware Error x 3",
  "Uygulama, toplanan ham GPS verilerini nihai bir koordinata dönüştürmek için 4 farklı matematiksel model sunar. Bu yöntemleri <b>Ayarlar</b> menüsünden değiştirebilirsiniz:": "The application provides 4 separate mathematical models to filter and process the gathered raw GNSS coordinates. You can toggle these anytime via <b>Settings</b>:",
  "Uygulama, toplanan ham GPS/GNSS verilerini nihai bir koordinata dönüştürmek için 7 farklı gelişmiş akademik model sunar.": "The computational engine provides seven distinct state-of-the-art geodetic adjustment models to resolve collected raw GPS/GNSS observables into precise coordinate vectors.",
  "TEMEL": "BASIC",
  "Veri setindeki tüm koordinatların basit aritmetik ortalamasını hesaplar. Tüm veriler eşit ağırlığa sahiptir.": "Calculates the simple unweighted centroid of the sample cloud. Highly stable when outliers are absent.",
  "VARSAYILAN": "DEFAULT",
  "Veri setindeki donanımsal hassasiyeti yüksek olan verilere daha fazla ağırlık vererek dengeleme yapar. En kararlı sonuçları üretir.": "Applies a Least Squares inverse-variance weight logic. Gives greater influence to coordinates collected during moments of low estimated error.",
  "İstatistik yöntemler kullanılarak uygulamaya özel olarak iyileştirilmiş hibrit bir yöntemdir.": "An advanced hybrid mathematical filter custom-designed for this application to reject spatial outliers:",
  "İşlem Adımları:": "Process Steps:",
  "Uzaysal Kol (K-Means Bölge Tespiti)": "Spatial Branch (K-Means Region Detection)",
  "Ham veriler mekansal yakınlıklarına göre kümelenerek en çok örneklem barındıran 'Şampiyon Küme' seçilir. Bu küme, çoklu yol yansımalarından arındırılmış 'Güvenli Geometrik Bölge' olarak tescillenir.": "Raw coordinates are clustered by spatial proximity, selecting the largest 'Champion Cluster'. This cluster is registered as the 'Safe Geometric Region' free from multipath distortions.",
  "Jeodezik Kol (Hodges-Lehmann Testi)": "Geodetic Branch (Robust Hodges-Lehmann Testing)",
  "Veri setinin tamamı bölünmeden tek bir büyük grup olarak bütünsel Hodges-Lehmann robust analizine sokulur. Makro düzeyde temizlenmiş, gürültülerden arınmış bir puan havuzu elde edilir.": "The entire dataset is subjected to a global Hodges-Lehmann reliability analysis as one single group, obtaining a macro-clean pool of points.",
  "Kesişim Filtresi ve Lokal Gelişmiş Ayıklama (Seçenek C)": "Intersection Filter & Local Outlier Removal (Option C)",
  "Hodges-Lehmann analizinden temiz çıkan noktalar ile K-Means Şampiyon Kümesindeki noktaların doğrudan indeks kesişimi alınarak çifte denetim sağlanır. Eğer kesişim kümesi boş kalırsa, şampiyon kümenin kendi iç varyansına yerel Hodges-Lehmann uygulanarak lokal aykırı değerler elenir.": "The intersection between globally clean Hodges-Lehmann nodes and the K-Means Champion cluster indices provides recursive validation. If the intersection is empty, a localized Hodges-Lehmann test runs on the champion cluster points to eliminate outliers.",
  "Hassas Ağırlıklı Dengeleme (WLS)": "Precise Weighted Adjustment (WLS)",
  "Elde edilen nihai süzülmüş noktalar, donanımsal hassasiyet ağırlıkları (1/accuracy²) gözetilerek Stokastik En Küçük Kareler (WLS) dengelemesine sokulur ve üstün stabilitede bir koordinat çözümü üretilir.": "The final refined subset is computed via Weighted Least Squares (WLS) based on inverse-variance weights (1/accuracy²) to deliver an exceptionally stable coordinate estimate.",
  "Konum Teknolojisi": "Positioning Technology",
  "Uygulama, en yüksek hassasiyeti sağlamak için <b>Hibrit (Karma) Konumlama</b> teknolojisini kullanır. Bu teknoloji, aşağıdaki 4 kaynağı birleştirerek çalışır:": "To maximize geodetic positioning times, the system works through a <b>Hybrid Positioning Architecture</b>, combining 4 key signals:",
  "1. GNSS (Uydu)": "1. GNSS (Constellations)",
  "GPS, GLONASS, Galileo ve BeiDou uydularından gelen sinyalleri kullanır. Açık alanda hassas (±2m) konum verisi sağlar.": "Reads sub-meter orbits from GPS (US), GLONASS (RU), Galileo (EU), and BeiDou (CN). Yields high precision (down to ±2m) in sky-clear fields.",
  "2. Baz İstasyonları": "2. Cell Tower Trilateration",
  "Uyduların görülemediği kapalı alanlarda veya tünellerde, telefonunuzun bağlı olduğu baz istasyonlarına göre yaklaşık konum belirler. Hassiyeti düşüktür.": "Triangulates based on cell tower sector transceivers. Highly useful as a fallback indoors or in dense tunnels but with low accuracy.",
  "3. Wi-Fi Ağları": "3. Wi-Fi Positioning (WPS)",
  "Şehir içinde bina aralarında, çevredeki kablosuz ağların sinyal gücünü kullanarak konumu keskinleştirir (IPS). Hassiyeti oldukça düşüktür.": "Utilizes localized BSSIDs and signal strengths to estimate position in concrete canyons. Highly resilient but of low metrological accuracy.",
  "4. A-GPS (İnternet)": "4. Assisted GPS (Internet)",
  "İnternet üzerinden güncel uydu yörünge verilerini (almanak) indirerek, GPS'in saniyeler içinde kilitlenmesini (Fix) sağlar. Hassiyeti oldukça düşüktür.": "Downloads immediate ephemeris and almanac tables over internet protocols, reducing satellite acquisition time (Time-To-First-Fix/TTFF) from minutes to seconds.",
  "ED50 Dönüşümü": "ED50 Helmer Transformation",
  "WGS84 ile ED50 (European Datum 1950) arasındaki dönüşümler, Türkiye geneli için optimize edilmiş 7 Parametreli (dX, dY, dZ, Rx, Ry, Rz, dS \"HGM/EPSG Standartları\") Helmert Dönüşümü kullanılarak yapılmaktadır.": "Geodetic transitions between WGS84 and ED50 (European Datum 1950) are computed via a Turkey-wide optimized 3D 7-Parameter (Helmert) transform adhering to institutional standards (HGM/EPSG specs).",
  "WGS84 ile ED50 arasındaki dönüşümler, 3 ötemele parametresi kullanan (HGM/EPSG Standartları) Helmert Dönüşümü kullanılarak yapılmaktadır.": "Datum transformations from WGS84 coordinates to national ED50 endpoints are resolved via a 3-parameter conformal coordinate shift model conforming to statutory Turkish HGM & EPSG standards.",
  "ITRF96 Dönüşümü": "ITRF96 Grid Projection",
  "ITRF96 (GRS80 Elipsoidi) koordinatları, Transversal Mercator (TM) projeksiyonu ile hesaplanmaktadır. 3° dilim genişliği ve dilim orta meridyenleri (DOM) otomatik belirlenir.": "Transversal Mercator (TM) map equations project geocentric WGS84/GRS80 coordinates into 3-degree TM or 6-degree UTM zones, dynamically solving Central Meridians (CM).",
  "Düşey Datum (Yükseklik)": "Vertical Datum & Geoid Ondulation",
  "Ortometrik Yükseklik (H), GPS'ten alınan Elipsoid yüksekliğinden (h), TG-20 Jeoid Modeli ondülasyon değeri (N) çıkarılarak hesaplanır.": "Orthometric elevations (H) are solved by subtracting localized geoid heights (N) from the ellipsoidal height (h), mapped from TG-20/EGM96 5'x5' models.",
  "Verileriniz tamamen cihazınızda saklanır. Uygulama, konum verilerinizi hiçbir uzak sunucuya göndermez. Mobil cihazınızdan uygulamayı sildiğinizde veya tarayıcı önbelliğini temizlediğinizde cihazınızdaki veriler de silinecektir. Ölçüm sonrası verilerinizi yedeklemeyi unutmayın.": "Your measurements are kept 100% locally. No locations are posted to cloud nodes. Uninstalling the app or wiping browser caches will reset the databases. Please back up measurements regularly.",
  "Sorumluluk Reddi": "Disclaimer / Geodetic Reliability",
  "Uygulama tarafından sağlanan verilerin doğruluğu ve hassasiyeti, mobil cihazınızın donanımsal (GPS/GNSS) alıcı kapasitesine, uydu görünürlüğüne ve çevresel faktörlere bağlıdır. Uygulama, profesyonel jeodezik ekipmanların yerini tutmaz. Elde edilen verilerin kritik mühendislik projelerinde kullanılmadan önce profesyonel ekipmanlarla doğrulanması önerilir. Oluşabilecek hatalardan veya veri kayıplarından yazılım geliştiricisi sorumlu tutulamaz.": "Accuracy values correspond to internal mobile receiver limitations, GNSS satellite counts, and outdoor conditions. This application is not a replacement for high-grade multi-band RTK receivers. Do not deploy these measurements on high-risk engineering work before confirming via professional instruments.",
  "Uygulamada kullanılan tüm veriler açık kaynaklı veya lisanslı servislerden sağlanmaktadır. Telif ihlali barındıran herhangi bir içerik bulunmamaktadır.": "All resources and coefficients integrated within this geodetic toolbox are compiled from trusted open sources and public standards.",
  "Konum Verisi": "GNSS Location Engine",
  "Geolocation API (WGS84 Format)": "Geolocation API (WGS84 Ellipsoid Format)",
  "React & React DOM (Modern UI Engine)": "React & React DOM (Modern UI Engine)",
  "Leaflet & React Leaflet (Interactive Spatial Map Engine)": "Leaflet & React Leaflet (Interactive Spatial Map Engine)",
  "Recharts (Statistical Plotting & Chart Services)": "Recharts (Statistical Plotting & Chart Services)",
  "html-to-image & FileSaver (Dynamic Snapshot Export Services)": "html-to-image & FileSaver (Dynamic Snapshot Export Services)",
  "Koordinat Dönüşümleri": "Transform Engine",
  "Custom Helmert & TM Projection Formulas (HGM/EPSG Standards)": "Geocentric Standard Helmert & Transverse Mercator (HGM/EPSG)",
  "Jeoid Modeli": "Geoid Models",
  "TG-20 (Çözünürlük: 5'x5')": "Turkish TG-20 Geoid Model Grid (5' x 5')",
  "EGM96 (Çözünürlük: 5'x5')": "Global EGM96 Geoid Ondulation Grid (5' x 5')",
  "EGM96 (Çözünürlük: 15'x15')": "EGM96 (Resolution: 15'x15')",
  "Harita Servisleri": "Base Layers & Mapping API",
  "Leaflet JS Open-Source Library": "Leaflet JS Mapping Library",
  "Google Maps API (Satellite/Hybrid)": "Google Maps Platform Layers (Satellite/Hybrid Imagery)",
  "OpenStreetMap Contributors": "OpenStreetMap Street Base Map Layers",
  "Yazılım Kütüphaneleri": "Software Dependencies",
  "Proj4js (Coordinate Transformations)": "Proj4js Coordinate Reprojection Port",
  "SheetJS & JSZip (Data Export Services)": "SheetJS (XLSX Writer) and JSZip",
  "Lucide React & Font Awesome (Icons)": "Lucide React & Font-Awesome Web Vector Engine",
  "GÜVENLİ SİNYAL (YEŞİL)": "RELIABLE SIGNAL (GREEN)",
  "ORTA GÜVENLİ SİNYAL (TURUNCU)": "MEDIUM RELIABILITY SIGNAL (ORANGE)",
  "DÜŞÜK GÜVENİLİR SİNYAL (KIRMIZI)": "LOW RELIABILITY SIGNAL (RED)",
  "GÜVENLİ (YEŞİL)": "RELIABLE (GREEN)",
  "ORTA GÜVEN (TURUNCU)": "MEDIUM RELIABILITY (ORANGE)",
  "GÜVENSİZ (KIRMIZI)": "UNRELIABLE (RED)",
  "GÜVENLİ SİNYAL": "RELIABLE SIGNAL",
  "ORTA GÜVENLİ SİNYAL": "MEDIUM RELIABILITY SIGNAL",
  "GÜVENSİZ SİNYAL": "UNRELIABLE SIGNAL",
  "DÜŞÜK GÜVEN Lİ SİNYAL (KIRMIZI)": "LOW CONFLICT SIGNAL (RED)",
  "DÜŞÜK GÜVEN": "LOW RELIABILITY",
  "SINYAL DURUMU": "SIGNAL STATUS",
  "Veri Saçılım Özeti": "Data Spread Summary",
  "Maksimum Saçılım Genişliği:": "Maximum Spread Width:",
  "Konumsal Standart Sapma (1σ):": "Spatial Standard Deviation (1σ):",
  "Alıcı Sensör Hassasiyeti:": "Receiver Sensor Accuracy:",
  "Geodezik Sinyal Raporu / Yorumu:": "Geodetic Signal Report / Interpretation:",
  "Güvenilir Veri (Yeşil Sinyal)": "Reliable Data (Green Signal)",
  "Veriler yüksek tutarlılıktadır.": "Data readings have high consistency.",
  "Kriter: Donanımsal Hassasiyet ≤ 5m, Veri Saçılımı ≤ 5m, Veri Sayısı ≥ 15": "Criteria: Hardware Accuracy ≤ 5m, Coordinate Spread ≤ 5m, Sample Count ≥ 15",
  "UYARI: Sinyal yeşildir fakat maksimum saçılım alıcı sensörün donanımsal hassasiyetinden fazla olduğu için hafif çoklu yansıma (multipath) etkisi mevcuttur.": "WARNING: Signal is green, but maximum spread exceeds the hardware accuracy, indicating a marginal multipath (signal reflection) effect.",
  "Konumsal dağılım son derece stabil ve kümelenmiştir, multipath / sapma etkisi saptanmamıştır.": "Spatial distribution is highly stable and clustered; no significant multipath/drift detected.",
  "VERİ AZ (TURUNCU SİNYAL)": "SPARSE DATA (ORANGE SIGNAL)",
  "ORTA GÜVENLİ VERİ (TURUNCU SİNYAL)": "MEDIUM RELIABILITY DATA (ORANGE SIGNAL)",
  "Veriler orta tutarlılıktadır.": "Data readings have moderate consistency.",
  "Kriterler: 5m < Donanımsal Hassasiyet ≤ 20m veya 5m < Veri Saçılımı ≤ 20m veya Veri Saçılımı > Donanımsal Hassasiyet veya Veri Sayısı < 15": "Criteria: 5m < Hardware Acc ≤ 20m OR 5m < Data Spread ≤ 20m OR Coordinate Spread > Hardware Accuracy OR Sample Count < 15",
  "GÜVENSİZ VERİ (KIRMIZI SİNYAL)": "UNRELIABLE DATA (RED SIGNAL)",
  "Veriler yüksek oranda sapmalı ve güvensizdir.": "Data coordinates have extreme dispersion and are unreliable.",
  "Kriterler: Donanımsal Hassasiyet > 20m veya Veri Saçılımı > 20m veya Veri Saçılımı > Donanımsal Hassasiyet x 3": "Criteria: Hardware Accuracy > 20m OR Data Spread > 20m OR Data Spread > Hardware Accuracy x 3",
  "4. VERI SACILIMI VE SINYAL GUVENILIRLIK OZETI": "4. DATA SPREAD AND SIGNAL RELIABILITY SUMMARY",
  "Maksimum Saçılım Genişliği (Spread):": "Maximum Spatial Spread Width:",
  "Ortalama Alıcı Sensör Hassasiyeti:": "Average Receiver Sensor Accuracy:",
  "Sinyal Güvenilirlik Durumu:": "Signal Reliability Status:",
  "Geodezik Analiz Genel Yorumu:": "Geodetic Analysis Summary/Interpretation:",
  "Veriler yüksek oranda sapmalı ve güvensizdir. Kriterler: Donanımsal Hassasiyet > 20m, Veri Saçılımı > 20m veya Veri Saçılımı > Donanımsal Hassasiyet * 3": "Data readings have high dispersion and are unreliable. Criteria: Hardware Accuracy > 20m, Data Spread > 20m, or Data Spread > Hardware Accuracy * 3",
  "GÜVENİLİR VERİ (YEŞİL SİNYAL)": "RELIABLE DATA (GREEN SIGNAL)",
  "Veriler yüksek tutarlılıktadır. Ancak maksimum saçılım alıcı sensörün donanımsal hassasiyetinden fazla olduğu için hafif çoklu yansıma (multipath) etkisi mevcuttur.": " Readings are highly consistent. However, since maximum spread exceeds hardware sensor accuracy, a slight multipath interference was detected.",
  "Veriler yüksek tutarlılıktadır. Çoklu yansıma (multipath) veya sapma (drift) etkisi gözlenmemiştir. Sinyal kalitesi son derece güvenli seviyededir.": "Readings are highly consistent. No multipath reflection or spatial drift detected. Signal quality is optimal and highly reliable.",
  "VERİ AZ / ORTA GÜVENLİ VERİ (TURUNCU SİNYAL)": "SPARSE DATA / MEDIUM RELIABILITY (ORANGE SIGNAL)",
  "Veriler orta tutarlılıktadır. Kriterler: 5m < Donanımsal Hassasiyet <= 20m veya 5m < Veri Saçılımı <= 20m veya Veri Saçılımı > Donanımsal Hassasiyet veya Veri Sayısı < 15": "Readings have moderate consistency. Criteria: 5m < Hardware Acc <= 20m OR 5m < Data Spread <= 20m OR Coordinate Spread > Hardware Accuracy OR Sample Count < 15",
  "Bu uygulama, saha çalışmalarında hızlı ve pratik koordinat ölçümü, aplikasyon ve veri yönetimi sağlamak ve basit CBS verisi toplamak amacıyla geliştirilmiştir. Uygulama ile ilgili herhangi bir sorun yaşıyorsanız veya bir özellik isteğiniz varsa e-posta yoluyla iletişime geçebilirsiniz.": "This geodetic app was designed to streamline rapid geomatics, local cadastral staking, and asset logging offline in the field. If you run into issues or have feature requests, feel free to send us an email.",
  "Bu uygulama, saha çalışmalarında hızlı ve pratik koordinat ölçümü, aplikasyon ve veri yönetimi sağlamak ve basit CBS verisi toplamak amacıyla geliştirilmiştir.": "This mobile geodetic application is designed to achieve rapid, high-precision coordinate observation, cadastral staking, and spatial asset collection directly in the field.",
  "İletişim": "Contact / Feedback",
  "acbmaps@gmail.com": "acbmaps@gmail.com",
  "Seçilen profesyonel istatistik yöntemi için en az 30 epok veri gereklidir. Ölçümünüzde 30 epok altında veri bulunduğu için konumunuz otomatik olarak Ağırlıklı En Küçük Kareler (Weighted LSE) yöntemi ile kararlı hale getirilmiştir.": "At least 30 epochs of data are required for the selected professional statistical method. Since your measurement contains less than 30 epochs of data, your position has been stabilized automatically using the Weighted Least Squares (Weighted LSE) method.",
  "Kullanılan Yöntem:": "Method Used:",
  "Kullanılan Yöntem": "Method Used",
  "Yöntem:": "Method:",
  "Gözlemleri mekansal yakınlıklarına göre 4 bağımsız yoğunluk grubuna ayırarak küme merkezini belirler.": "Clusters observation points into 4 independent density groups based on geospatial distance to establish a cluster centroid.",
  "Gözlemleri mekansal yakınlıklarına göre dinamik sayıda yoğunluk grubuna ayırarak küme merkezini belirler.": "Clusters observation points into a dynamic number of density groups based on geospatial distance to establish a cluster centroid.",
  "Hodges-Lehmann kalın hata eleme teorisini kullanarak uyuşumsuz ve kaba hatalı koordinatları sistemden temizler.": "Iteratively purges outliers and gross coordinate errors from the dataset using geodetic Hodges-Lehmann robust testing.",
  "En az 30 epok veri gerektirir.": "Requires at least 30 epochs of data.",
  "En az 60 epok veri gerektirir.": "Requires at least 60 epochs of data.",
  "KMeans, Hodges-Lehmann ve K-Means + Hodges-Lehmann + WLS yöntemleri için en az 30 epok (veri sayısı) toplanmış olması şarttır. Daha az veri içeren durumlarda, bu profesyonel yöntemler yerine otomatik olarak Ağırlıklı En Küçük Kareler yöntemi ile güvenli bir biçimde hesaplama yapılır.": "A minimum of 30 epochs is strictly required for KMeans, Hodges-Lehmann, and K-Means + Hodges-Lehmann + WLS hybrid models. If less than 30 samples are collected, the system automatically and securely resolves the coordinates using the Weighted Least Squares (LSE) method.",
  "KMeans, Hodges-Lehmann, KMeans + Hodges-Lehmann ve KMeans + Hodges-Lehmann + Huber yöntemleri için en az 30 epok (veri sayısı) toplanmış olması şarttır. Daha az veri içeren durumlarda, bu profesyonel yöntemler yerine otomatik olarak Ağırlıklı En Küçük Kareler yöntemi ile güvenli bir biçimde hesaplama yapılır.": "A minimum of 30 epochs is strictly required for KMeans, Hodges-Lehmann, KMeans + Hodges-Lehmann, and KMeans + Hodges-Lehmann + Huber hybrid models. If less than 30 samples are collected, the system automatically and securely resolves the coordinates using the Weighted Least Squares (LSE) method.",
  "KMeans, Hodges-Lehmann ve KMeans + Hodges-Lehmann + Huber yöntemleri için en az 30 epok (veri sayısı) toplanmış olması şarttır. Daha az veri içeren durumlarda, bu profesyonel yöntemler yerine otomatik olarak Ağırlıklı En Küçük Kareler yöntemi ile güvenli bir biçimde hesaplama yapılır.": "A minimum of 30 epochs is strictly required for KMeans, Hodges-Lehmann, and KMeans + Hodges-Lehmann + Huber hybrid models. If less than 30 samples are collected, the system automatically and securely resolves the coordinates using the Weighted Least Squares (LSE) method.",
  "KMeans ve Huber yöntemleri için en az 30 epok; Hodges-Lehmann ve KMeans + Hodges-Lehmann + Huber hibrit yöntemleri için en az 60 epok (veri sayısı) toplanmış olması şarttır. Daha az veri içeren durumlarda, bu profesyonel yöntemler yerine otomatik olarak Ağırlıklı En Küçük Kareler yöntemi ile güvenli bir biçimde hesaplama yapılır.": "A minimum of 30 epochs is required for KMeans and Huber, and at least 60 epochs for Hodges-Lehmann and KMeans + Hodges-Lehmann + Huber hybrid models. If fewer samples are collected, the system automatically and securely falls back to the Weighted Least Squares (LSE) method.",
  "Akademik Teknik Rapor": "Academic Technical Report",
  "Uygulamanın akademik arka planını, istatistiksel ve jeodezik hesaplama yöntemlerini, TUSAGA-Aktif ve BÖHHBÜY uyumluluğunu içeren detaylı teknik rapor dökümanı.": "A comprehensive geodetic document drafting the mathematical formulations, statistical filtering models, 3D Helmert projections, and compliance with Turkish TUSAGA-Aktif & BÖHHBÜY national cadastral standards.",
  "Oturum": "Session",
  "Oturum No": "Session No"
};

/**
 * Translates a Turkish text key to English if current language is 'EN'.
 * If the key is not found, or language is 'TR', returns the original.
 */
export function t(key: string, lang: string): string {
  if (lang === 'EN') {
    return trToEnMap[key] || key;
  }
  return key;
}
